export type dropCheck = { checked: boolean; value: string };

export const filterTrueValues = (arr: dropCheck[]) => {
  const value = arr?.filter(cur => cur.checked).map(cur => cur.value);

  return value;
};

export const facilities = [
  'ICU',
  'MICU',
  'CICU',
  'NICU',
  'PICU (Pediatrics ICU)',
  'IPD',
  'OPD',
  'Emergency and Trauma',
  'Laboratory',
  'Imaging',
  'Pharmacy',
  'Transplant Immunology and Immunogenetics',
  'Labour Room',
  'Blood Banks',
  'Blood Storage',
  'Eye Bank',
  'Organ Bank',
  'Ambulance',
  'Dialysis Unit',
  'Operation Theater',
  'Physiotherapy',
  'Occupational Therapy',
  'Diagnostics',
  'Medical Tourism',
  // 'Any Other +'
];

export const specialities = [
  'Anaesthesiology',
  'Anatomy',
  'Bariatric Surgery',
  'Biochemistry',
  'Biomedical Engineering',
  'Biophysics',
  'Biostatistics',
  'Biotechnology',
  'Burn Department',
  'Cardiology',
  'Cardio Thoracic Vascular Surgery',
  'Centre for Community Medicine',
  'Cosmetic Surgery',
  'Dermatology and Venereology',
  'Dietetics',
  'Dental',
  'Endocrinology, Metabolism and Diabetes',
  'Forensic Medicine and Toxicology',
  'Gastroenterology and Human Nutrition',
  'Gastrointestinal SurgeryGeneral Surgery',
  'Hematology',
  'Internal Medicine',
  'Kidney Transplant',
  'Laboratory Medicine',
  'Liver Transplant',
  'Laparoscopic Surgery',
  'Medicine',
  'Microbiology',
  'Nephrology',
  'Nuclear Medicine',
  'Neurology',
  'Neuron Surger',
  'Nuclear Magnetic Resonance Imaging',
  'Obstetrics and Gynaecology',
  'In Vitro Fertilization (IVF)',
  'Oncology/ Oncosurgery (Cancer Care)',
  'Orthopedics',
  'Ophthalmology (Eye Care)',
  'Otorhinolaryngology (Ear Nose and Throat)',
  'Pediatrics',
  'Pediatric Surgery',
  'Pulmonology/ Respiratory Medicine',
  'Trauma and Emergency Medicine',
  'Plastic Surgery (Reconstructive Surgery)',
  'Pharmacology',
  'Physiology',
  'Physical Medicine and Rehabilitation',
  'Psychiatry',
  'Reproductive Biology',
  'Surgical Disciplines',
  'Transplant Surgery',
  'Transfusion Medicine (Blood Bank)Urology',
  'Vascular Surgery',
  // 'Any Other +'
];

export const testTable = [
  {
    type: 'credit',
    date: '1/1/2021',
    details: 'bought diclophenac',
    amount: '200',
    balance: '400',
  },
  {
    type: 'debit',
    date: '2/1/2021',
    details: 'bought diclophenac',
    amount: '200',
    balance: '400',
  },
  {
    type: 'card',
    date: '3/1/2021',
    details: 'bought diclophenac',
    amount: '200',
    balance: '400',
  },
  {
    type: 'debit',
    date: '4/1/2021',
    details: 'bought diclophenac',
    amount: '200',
    balance: '400',
  },
  {
    type: 'card',
    date: '5/1/2021',
    details: 'bought diclophenac',
    amount: '200',
    balance: '400',
  },
  {
    type: 'debit',
    date: '6/1/2021',
    details: 'bought diclophenac',
    amount: '200',
    balance: '400',
  },
  {
    type: 'card',
    date: '7/1/2021',
    details: 'bought diclophenac',
    amount: '200',
    balance: '400',
  },
  {
    type: 'debit',
    date: '8/1/2021',
    details: 'bought diclophenac',
    amount: '200',
    balance: '400',
  },
  {
    type: 'card',
    date: '9/1/2021',
    details: 'bought diclophenac',
    amount: '200',
    balance: '400',
  },
  {
    type: 'debit',
    date: '10/1/2021',
    details: 'bought diclophenac',
    amount: '200',
    balance: '400',
  },
  {
    type: 'card',
    date: '11/1/2021',
    details: 'bought diclophenac',
    amount: '200',
    balance: '400',
  },
  {
    type: 'debit',
    date: '12/1/2021',
    details: 'bought diclophenac',
    amount: '200',
    balance: '400',
  },
  {
    type: 'card',
    date: '13/1/2021',
    details: 'bought diclophenac',
    amount: '200',
    balance: '400',
  },
  {
    type: 'debit',
    date: '14/1/2021',
    details: 'bought diclophenac',
    amount: '200',
    balance: '400',
  },
  {
    type: 'card',
    date: '15/1/2021',
    details: 'bought diclophenac',
    amount: '200',
    balance: '400',
  },
  {
    type: 'debit',
    date: '16/1/2021',
    details: 'bought diclophenac',
    amount: '200',
    balance: '400',
  },
  {
    type: 'card',
    date: '17/1/2021',
    details: 'bought diclophenac',
    amount: '200',
    balance: '400',
  },
  {
    type: 'debit',
    date: '18/1/2021',
    details: 'bought diclophenac',
    amount: '200',
    balance: '400',
  },
  {
    type: 'card',
    date: '19/1/2021',
    details: 'bought diclophenac',
    amount: '200',
    balance: '400',
  },
  {
    type: 'debit',
    date: '20/1/2021',
    details: 'bought diclophenac',
    amount: '200',
    balance: '400',
  },
  {
    type: 'card',
    date: '21/1/2021',
    details: 'bought diclophenac',
    amount: '200',
    balance: '400',
  },
];
